# Generated by Django 5.0.6 on 2024-05-28 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Kinds",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kind", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("about", models.TextField()),
                ("price", models.FloatField()),
                ("image", models.ImageField(upload_to="product_image")),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                (
                    "knds_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="product.kinds"
                    ),
                ),
            ],
        ),
    ]
